<?php /** @var $this \Project\Applications\Www\Views\Index */ ?>
<div class="row-fluid">
  <div class="span6">
    <h4>Subheading</h4>

    <p>This section is pure html which can be found in templates/index.phtml</p>

    <h4>Subheading</h4>

    <p>By adding a PHP comment to define @var $this within your view, you can get hinting
      for your view model</p>
  </div>
  <div class="span6">
    <h4>Subheading</h4>

    <p>This section is pure html which can be found in templates/index.phtml</p>

    <h4>Subheading</h4>

    <p>By adding a PHP comment to define @var $this within your view, you can get hinting
      for your view model</p>
  </div>
</div>
<hr/>
