<?php /** @var $this \Project\Applications\Www\Views\Index */ ?>
<div class="row-fluid">
  <div class="span6">
    <h4><?php echo $this->t('Subheading'); ?></h4>

    <p><?php echo $this->t('This section is pure html which can be found in templates/index.phtml'); ?></p>

    <h4><?php echo $this->t('Subheading'); ?></h4>

    <p><?php echo $this->t('By adding a PHP comment to define @var $this within your view, you can get hinting
      for your view model'); ?></p>
  </div>
  <div class="span6">
    <h4><?php echo $this->t('Subheading'); ?></h4>

    <p><?php echo $this->t('This section is pure html which can be found in templates/index.phtml'); ?></p>

    <h4><?php echo $this->t('Subheading'); ?></h4>

    <p><?php echo $this->t('By adding a PHP comment to define @var $this within your view, you can get hinting
      for your view model'); ?></p>
  </div>
</div>
<hr/>
