<?php
/**
 *
 * @var $this \Cubex\View\Layout
 *
 * This is your default layout file, variables in this file act as placeholders for named nested views
 *
 */
?>
<div class="container-narrow" id="wrapper">

  <div class="masthead">
    <ul class="nav nav-pills pull-right">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="/about">About</a></li>
      <li><a href="/contact">Contact</a></li>
    </ul>
    <h3 class="muted"><?php
      $app = $this->entity();
      if($app instanceof \Cubex\Core\Application\Application)
      {
        echo $app->name();
      }
      else
      {
        echo "Unknown";
      }
      ?></h3>
  </div>
  <hr>
  <div id="header"><?php echo $this->renderNest("header", false); ?></div>

  <hr>
  <div id="content">
    <?php echo $this->renderNest("content", "main-content"); ?>
    <div class="clear">&nbsp;</div>
  </div>

</div>
