<?php
/**
 *
 * @var $this \Cubex\View\Layout
 *
 * This is your default layout file, variables in this file act as placeholders for named nested views
 *
 */
?>
<div class="container-narrow" id="wrapper">

  <div class="masthead">
    <ul class="nav nav-pills pull-right">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="http://cubex.io">Cubex.io</a></li>
    </ul>
    <h3 class="muted">Your New Cubex Application</h3>
  </div>
  <hr>
  <div id="content">
    <?php echo $this->renderNest("content", "main-content"); ?>
  </div>

</div>
